@domain = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDM3NTM1Mjh9.RNlVOtcLGKl9KOyzbi5fr6quCo2fcKOfSeQRblSp7NM

GET {{ domain }}/movies

###

GET {{ domain }}/movies

###
GET {{ domain }}/actors

###
POST {{ domain }}/actors

Content-Type: application/json

{
  "first_name": "Matt",
  "last_name": "Damon",
  "known_for": "How do you like them apples?"
}

###

DELETE {{ domain }}/actors/6

### 

POST {{ domain }}/movies
Content-Type: application/json

{
  "title": "Lion King",
  "year": 1993,
  "plot": "Hakuna Matata"
}

###
PATCH {{ domain }}/movies/3
Content-Type: application/json

{
  "year": 1920
}

### Users create (signup)
POST {{ domain }}/users
Content-Type: application/json

{
  "name": "Barry",
  "email": "Crockett",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{ domain }}/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### MovieGenre create
POST {{ domain }}/movie_genres/
Content-Type: application/json

{
  "movie_id": 1,
  "genre_id": 1
}